### ISSUE TITLE
Error occurred while enabling KeepChunks

### ISSUE THREAD

**Issue by VacantFiend** [Geitenijs/KeepChunks#2]
Following error message occurs on server start.

```
[09:55:57] [Server thread/ERROR]: Error occurred while enabling KeepChunks v1.5.9 (Is it up to date?)
java.lang.NumberFormatException: For input string: "uns"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_191]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_191]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_191]
	at com.geitenijs.keepchunks.Hooks.hookWorldEdit(Hooks.java:31) ~[?:?]
	at com.geitenijs.keepchunks.Hooks.registerHooks(Hooks.java:16) ~[?:?]
	at com.geitenijs.keepchunks.Main.onEnable(Main.java:16) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-495]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[09:55:57] [Server thread/INFO]: [KeepChunks] Disabling KeepChunks v1.5.9
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Server Software: Paper 495
 - Server Version: 1.13.2
 - WorldEdit Version: FastAsyncWorldEdit 1.13.132
 - WorldGuard Version: N/A
 - Full list of plugins
Boss 1.8.16
CoreProtect 2.15.1
DynMap 3.0 Beta 3
EditMobs
InventoryRollback 1.3.3
ProtocolLib

**Comment by VacantFiend** [comment]
Removing FAWE resolves the issue.

**Comment by Geitenijs** [comment]
Thanks for reporting. KeepChunks v1.5.10 will no longer drop an error in the console, however we still don't support FAWE.
