### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by eserkesar** [Geitenijs/KeepChunks#67]
**Describe the bug**
Cannot execute any command that is somehow related to worldguard

**To Reproduce**
1. Execute command '/kc chunkinfo worldguard dungeon4 world' or '/kc keepregion worldguard dungeon4 world'
2. Use feature 'worldguard'
3. [02:50:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'kc' in plugin KeepChunks v1.7.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-497]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'int com.sk89q.worldedit.math.BlockVector3.x()'
        at com.geitenijs.keepchunks.commands.hooks.Keepregion_WG.onCommand(Keepregion_WG.java:47) ~[KeepChunks-1.7.2.jar:?]
        at com.geitenijs.keepchunks.commands.Command_Keepregion.onCommand(Command_Keepregion.java:56) ~[KeepChunks-1.7.2.jar:?]
        at com.geitenijs.keepchunks.commands.CommandWrapper.onCommand(CommandWrapper.java:128) ~[KeepChunks-1.7.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more

**Expected behavior**
To claim/register an entire region of worldguard using keepchunk.

**Screenshots**
![image](https://github.com/user-attachments/assets/b8fc596b-5cd7-4dec-87ef-a57eadb6ebc0)

**Environment (please complete the following information):**
 - OS: [Hosting Server]
 - Server Software [Paper]
 - Server Version [1.20.4]
 - FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-776.jar
 - worldguard-bukkit-7.0.9-dist.jar
 - *non related to world modification

**Comment by Geitenijs** [comment]
This is due to WE/WG changing their API. I've updated KeepChunks accordingly, but you're running older versions of both WE and WG.

Now, I don't think you can run a newer version of WG on 1.20.4, but try updating FAWE to build [#879](https://ci.athion.net/job/FastAsyncWorldEdit/879/) or newer. If that doesn't work, update your server to 1.21 and update WG to 7.0.11 OR use KeepChunks v1.7.1
